# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JavaEnvSwitch(object):
    def setupUi(self, JavaEnvSwitch):
        JavaEnvSwitch.setObjectName("JavaEnvSwitch")
        JavaEnvSwitch.resize(441, 90)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        JavaEnvSwitch.setFont(font)
        JavaEnvSwitch.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(JavaEnvSwitch)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(0, 40, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 361, 31))
        self.label.setObjectName("label")
        self.btn_load = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load.setGeometry(QtCore.QRect(360, 10, 81, 21))
        self.btn_load.setObjectName("btn_load")
        JavaEnvSwitch.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(JavaEnvSwitch)
        self.statusbar.setObjectName("statusbar")
        JavaEnvSwitch.setStatusBar(self.statusbar)

        self.retranslateUi(JavaEnvSwitch)
        QtCore.QMetaObject.connectSlotsByName(JavaEnvSwitch)

    def retranslateUi(self, JavaEnvSwitch):
        _translate = QtCore.QCoreApplication.translate
        JavaEnvSwitch.setWindowTitle(_translate("JavaEnvSwitch", "JavaEnvSwitcher"))
        self.pushButton.setText(_translate("JavaEnvSwitch", "switch"))
        self.label.setText(_translate("JavaEnvSwitch", "TextLabel"))
        self.btn_load.setText(_translate("JavaEnvSwitch", "LoadLocalPath"))
